### ISSUE TITLE
unable to initialize bot

### ISSUE THREAD

**Issue by 7ekhed** [Ocelotworks/OcelotBOT#7]
I am unsure how to initialize the bot, but i have tried every .js file in the folder, and I think that it is booted off of the ocelotbot.js. But when I boot it, an error comes up saying:

module.js:557
    throw err;
    ^

Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\johan\Desktop\OcelotBOT-master\ocelotbot.js:6:23)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

plz help!

**Comment by LiamDevJS** [comment]
You need to install the node module "mysql".  You can install just this module by using the command `npm install mysql`, or you can install all modules and dependencies by using `npm install`.
